<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<!-- saved from url=(0014)about:internet -->
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">

<title>Quick examination of data</title>

<base target="_blank"/>

<style type="text/css">
body, td {
   font-family: sans-serif;
   background-color: white;
   font-size: 12px;
   margin: 8px;
}

tt, code, pre {
   font-family: 'DejaVu Sans Mono', 'Droid Sans Mono', 'Lucida Console', Consolas, Monaco, monospace;
}

h1 { 
   font-size:2.2em; 
}

h2 { 
   font-size:1.8em; 
}

h3 { 
   font-size:1.4em; 
}

h4 { 
   font-size:1.0em; 
}

h5 { 
   font-size:0.9em; 
}

h6 { 
   font-size:0.8em; 
}

a:visited {
   color: rgb(50%, 0%, 50%);
}

pre {	
   margin-top: 0;
   max-width: 95%;
   border: 1px solid #ccc;
}

pre code {
   display: block; padding: 0.5em;
}

code.r {
   background-color: #F8F8F8;
}

table, td, th {
  border: none;
}

blockquote {
   color:#666666;
   margin:0;
   padding-left: 1em;
   border-left: 0.5em #EEE solid;
}

hr {
   height: 0px;
   border-bottom: none;
   border-top-width: thin;
   border-top-style: dotted;
   border-top-color: #999999;
}

@media print {
   * { 
      background: transparent !important; 
      color: black !important; 
      filter:none !important; 
      -ms-filter: none !important; 
   }

   body { 
      font-size:12pt; 
      max-width:100%; 
   }
       
   a, a:visited { 
      text-decoration: underline; 
   }

   hr { 
      visibility: hidden;
      page-break-before: always;
   }

   pre, blockquote { 
      padding-right: 1em; 
      page-break-inside: avoid; 
   }

   tr, img { 
      page-break-inside: avoid; 
   }

   img { 
      max-width: 100% !important; 
   }

   @page :left { 
      margin: 15mm 20mm 15mm 10mm; 
   }
     
   @page :right { 
      margin: 15mm 10mm 15mm 20mm; 
   }

   p, h2, h3 { 
      orphans: 3; widows: 3; 
   }

   h2, h3 { 
      page-break-after: avoid; 
   }
}

</style>

<!-- Styles for R syntax highlighter -->
<style type="text/css">
   pre .operator,
   pre .paren {
     color: rgb(104, 118, 135)
   }

   pre .literal {
     color: rgb(88, 72, 246)
   }

   pre .number {
     color: rgb(0, 0, 205);
   }

   pre .comment {
     color: rgb(76, 136, 107);
   }

   pre .keyword {
     color: rgb(0, 0, 255);
   }

   pre .identifier {
     color: rgb(0, 0, 0);
   }

   pre .string {
     color: rgb(3, 106, 7);
   }
</style>

<!-- R syntax highlighter -->
<script type="text/javascript">
var hljs=new function(){function m(p){return p.replace(/&/gm,"&amp;").replace(/</gm,"&lt;")}function f(r,q,p){return RegExp(q,"m"+(r.cI?"i":"")+(p?"g":""))}function b(r){for(var p=0;p<r.childNodes.length;p++){var q=r.childNodes[p];if(q.nodeName=="CODE"){return q}if(!(q.nodeType==3&&q.nodeValue.match(/\s+/))){break}}}function h(t,s){var p="";for(var r=0;r<t.childNodes.length;r++){if(t.childNodes[r].nodeType==3){var q=t.childNodes[r].nodeValue;if(s){q=q.replace(/\n/g,"")}p+=q}else{if(t.childNodes[r].nodeName=="BR"){p+="\n"}else{p+=h(t.childNodes[r])}}}if(/MSIE [678]/.test(navigator.userAgent)){p=p.replace(/\r/g,"\n")}return p}function a(s){var r=s.className.split(/\s+/);r=r.concat(s.parentNode.className.split(/\s+/));for(var q=0;q<r.length;q++){var p=r[q].replace(/^language-/,"");if(e[p]){return p}}}function c(q){var p=[];(function(s,t){for(var r=0;r<s.childNodes.length;r++){if(s.childNodes[r].nodeType==3){t+=s.childNodes[r].nodeValue.length}else{if(s.childNodes[r].nodeName=="BR"){t+=1}else{if(s.childNodes[r].nodeType==1){p.push({event:"start",offset:t,node:s.childNodes[r]});t=arguments.callee(s.childNodes[r],t);p.push({event:"stop",offset:t,node:s.childNodes[r]})}}}}return t})(q,0);return p}function k(y,w,x){var q=0;var z="";var s=[];function u(){if(y.length&&w.length){if(y[0].offset!=w[0].offset){return(y[0].offset<w[0].offset)?y:w}else{return w[0].event=="start"?y:w}}else{return y.length?y:w}}function t(D){var A="<"+D.nodeName.toLowerCase();for(var B=0;B<D.attributes.length;B++){var C=D.attributes[B];A+=" "+C.nodeName.toLowerCase();if(C.value!==undefined&&C.value!==false&&C.value!==null){A+='="'+m(C.value)+'"'}}return A+">"}while(y.length||w.length){var v=u().splice(0,1)[0];z+=m(x.substr(q,v.offset-q));q=v.offset;if(v.event=="start"){z+=t(v.node);s.push(v.node)}else{if(v.event=="stop"){var p,r=s.length;do{r--;p=s[r];z+=("</"+p.nodeName.toLowerCase()+">")}while(p!=v.node);s.splice(r,1);while(r<s.length){z+=t(s[r]);r++}}}}return z+m(x.substr(q))}function j(){function q(x,y,v){if(x.compiled){return}var u;var s=[];if(x.k){x.lR=f(y,x.l||hljs.IR,true);for(var w in x.k){if(!x.k.hasOwnProperty(w)){continue}if(x.k[w] instanceof Object){u=x.k[w]}else{u=x.k;w="keyword"}for(var r in u){if(!u.hasOwnProperty(r)){continue}x.k[r]=[w,u[r]];s.push(r)}}}if(!v){if(x.bWK){x.b="\\b("+s.join("|")+")\\s"}x.bR=f(y,x.b?x.b:"\\B|\\b");if(!x.e&&!x.eW){x.e="\\B|\\b"}if(x.e){x.eR=f(y,x.e)}}if(x.i){x.iR=f(y,x.i)}if(x.r===undefined){x.r=1}if(!x.c){x.c=[]}x.compiled=true;for(var t=0;t<x.c.length;t++){if(x.c[t]=="self"){x.c[t]=x}q(x.c[t],y,false)}if(x.starts){q(x.starts,y,false)}}for(var p in e){if(!e.hasOwnProperty(p)){continue}q(e[p].dM,e[p],true)}}function d(B,C){if(!j.called){j();j.called=true}function q(r,M){for(var L=0;L<M.c.length;L++){if((M.c[L].bR.exec(r)||[null])[0]==r){return M.c[L]}}}function v(L,r){if(D[L].e&&D[L].eR.test(r)){return 1}if(D[L].eW){var M=v(L-1,r);return M?M+1:0}return 0}function w(r,L){return L.i&&L.iR.test(r)}function K(N,O){var M=[];for(var L=0;L<N.c.length;L++){M.push(N.c[L].b)}var r=D.length-1;do{if(D[r].e){M.push(D[r].e)}r--}while(D[r+1].eW);if(N.i){M.push(N.i)}return f(O,M.join("|"),true)}function p(M,L){var N=D[D.length-1];if(!N.t){N.t=K(N,E)}N.t.lastIndex=L;var r=N.t.exec(M);return r?[M.substr(L,r.index-L),r[0],false]:[M.substr(L),"",true]}function z(N,r){var L=E.cI?r[0].toLowerCase():r[0];var M=N.k[L];if(M&&M instanceof Array){return M}return false}function F(L,P){L=m(L);if(!P.k){return L}var r="";var O=0;P.lR.lastIndex=0;var M=P.lR.exec(L);while(M){r+=L.substr(O,M.index-O);var N=z(P,M);if(N){x+=N[1];r+='<span class="'+N[0]+'">'+M[0]+"</span>"}else{r+=M[0]}O=P.lR.lastIndex;M=P.lR.exec(L)}return r+L.substr(O,L.length-O)}function J(L,M){if(M.sL&&e[M.sL]){var r=d(M.sL,L);x+=r.keyword_count;return r.value}else{return F(L,M)}}function I(M,r){var L=M.cN?'<span class="'+M.cN+'">':"";if(M.rB){y+=L;M.buffer=""}else{if(M.eB){y+=m(r)+L;M.buffer=""}else{y+=L;M.buffer=r}}D.push(M);A+=M.r}function G(N,M,Q){var R=D[D.length-1];if(Q){y+=J(R.buffer+N,R);return false}var P=q(M,R);if(P){y+=J(R.buffer+N,R);I(P,M);return P.rB}var L=v(D.length-1,M);if(L){var O=R.cN?"</span>":"";if(R.rE){y+=J(R.buffer+N,R)+O}else{if(R.eE){y+=J(R.buffer+N,R)+O+m(M)}else{y+=J(R.buffer+N+M,R)+O}}while(L>1){O=D[D.length-2].cN?"</span>":"";y+=O;L--;D.length--}var r=D[D.length-1];D.length--;D[D.length-1].buffer="";if(r.starts){I(r.starts,"")}return R.rE}if(w(M,R)){throw"Illegal"}}var E=e[B];var D=[E.dM];var A=0;var x=0;var y="";try{var s,u=0;E.dM.buffer="";do{s=p(C,u);var t=G(s[0],s[1],s[2]);u+=s[0].length;if(!t){u+=s[1].length}}while(!s[2]);if(D.length>1){throw"Illegal"}return{r:A,keyword_count:x,value:y}}catch(H){if(H=="Illegal"){return{r:0,keyword_count:0,value:m(C)}}else{throw H}}}function g(t){var p={keyword_count:0,r:0,value:m(t)};var r=p;for(var q in e){if(!e.hasOwnProperty(q)){continue}var s=d(q,t);s.language=q;if(s.keyword_count+s.r>r.keyword_count+r.r){r=s}if(s.keyword_count+s.r>p.keyword_count+p.r){r=p;p=s}}if(r.language){p.second_best=r}return p}function i(r,q,p){if(q){r=r.replace(/^((<[^>]+>|\t)+)/gm,function(t,w,v,u){return w.replace(/\t/g,q)})}if(p){r=r.replace(/\n/g,"<br>")}return r}function n(t,w,r){var x=h(t,r);var v=a(t);var y,s;if(v){y=d(v,x)}else{return}var q=c(t);if(q.length){s=document.createElement("pre");s.innerHTML=y.value;y.value=k(q,c(s),x)}y.value=i(y.value,w,r);var u=t.className;if(!u.match("(\\s|^)(language-)?"+v+"(\\s|$)")){u=u?(u+" "+v):v}if(/MSIE [678]/.test(navigator.userAgent)&&t.tagName=="CODE"&&t.parentNode.tagName=="PRE"){s=t.parentNode;var p=document.createElement("div");p.innerHTML="<pre><code>"+y.value+"</code></pre>";t=p.firstChild.firstChild;p.firstChild.cN=s.cN;s.parentNode.replaceChild(p.firstChild,s)}else{t.innerHTML=y.value}t.className=u;t.result={language:v,kw:y.keyword_count,re:y.r};if(y.second_best){t.second_best={language:y.second_best.language,kw:y.second_best.keyword_count,re:y.second_best.r}}}function o(){if(o.called){return}o.called=true;var r=document.getElementsByTagName("pre");for(var p=0;p<r.length;p++){var q=b(r[p]);if(q){n(q,hljs.tabReplace)}}}function l(){if(window.addEventListener){window.addEventListener("DOMContentLoaded",o,false);window.addEventListener("load",o,false)}else{if(window.attachEvent){window.attachEvent("onload",o)}else{window.onload=o}}}var e={};this.LANGUAGES=e;this.highlight=d;this.highlightAuto=g;this.fixMarkup=i;this.highlightBlock=n;this.initHighlighting=o;this.initHighlightingOnLoad=l;this.IR="[a-zA-Z][a-zA-Z0-9_]*";this.UIR="[a-zA-Z_][a-zA-Z0-9_]*";this.NR="\\b\\d+(\\.\\d+)?";this.CNR="\\b(0[xX][a-fA-F0-9]+|(\\d+(\\.\\d*)?|\\.\\d+)([eE][-+]?\\d+)?)";this.BNR="\\b(0b[01]+)";this.RSR="!|!=|!==|%|%=|&|&&|&=|\\*|\\*=|\\+|\\+=|,|\\.|-|-=|/|/=|:|;|<|<<|<<=|<=|=|==|===|>|>=|>>|>>=|>>>|>>>=|\\?|\\[|\\{|\\(|\\^|\\^=|\\||\\|=|\\|\\||~";this.ER="(?![\\s\\S])";this.BE={b:"\\\\.",r:0};this.ASM={cN:"string",b:"'",e:"'",i:"\\n",c:[this.BE],r:0};this.QSM={cN:"string",b:'"',e:'"',i:"\\n",c:[this.BE],r:0};this.CLCM={cN:"comment",b:"//",e:"$"};this.CBLCLM={cN:"comment",b:"/\\*",e:"\\*/"};this.HCM={cN:"comment",b:"#",e:"$"};this.NM={cN:"number",b:this.NR,r:0};this.CNM={cN:"number",b:this.CNR,r:0};this.BNM={cN:"number",b:this.BNR,r:0};this.inherit=function(r,s){var p={};for(var q in r){p[q]=r[q]}if(s){for(var q in s){p[q]=s[q]}}return p}}();hljs.LANGUAGES.cpp=function(){var a={keyword:{"false":1,"int":1,"float":1,"while":1,"private":1,"char":1,"catch":1,"export":1,virtual:1,operator:2,sizeof:2,dynamic_cast:2,typedef:2,const_cast:2,"const":1,struct:1,"for":1,static_cast:2,union:1,namespace:1,unsigned:1,"long":1,"throw":1,"volatile":2,"static":1,"protected":1,bool:1,template:1,mutable:1,"if":1,"public":1,friend:2,"do":1,"return":1,"goto":1,auto:1,"void":2,"enum":1,"else":1,"break":1,"new":1,extern:1,using:1,"true":1,"class":1,asm:1,"case":1,typeid:1,"short":1,reinterpret_cast:2,"default":1,"double":1,register:1,explicit:1,signed:1,typename:1,"try":1,"this":1,"switch":1,"continue":1,wchar_t:1,inline:1,"delete":1,alignof:1,char16_t:1,char32_t:1,constexpr:1,decltype:1,noexcept:1,nullptr:1,static_assert:1,thread_local:1,restrict:1,_Bool:1,complex:1},built_in:{std:1,string:1,cin:1,cout:1,cerr:1,clog:1,stringstream:1,istringstream:1,ostringstream:1,auto_ptr:1,deque:1,list:1,queue:1,stack:1,vector:1,map:1,set:1,bitset:1,multiset:1,multimap:1,unordered_set:1,unordered_map:1,unordered_multiset:1,unordered_multimap:1,array:1,shared_ptr:1}};return{dM:{k:a,i:"</",c:[hljs.CLCM,hljs.CBLCLM,hljs.QSM,{cN:"string",b:"'\\\\?.",e:"'",i:"."},{cN:"number",b:"\\b(\\d+(\\.\\d*)?|\\.\\d+)(u|U|l|L|ul|UL|f|F)"},hljs.CNM,{cN:"preprocessor",b:"#",e:"$"},{cN:"stl_container",b:"\\b(deque|list|queue|stack|vector|map|set|bitset|multiset|multimap|unordered_map|unordered_set|unordered_multiset|unordered_multimap|array)\\s*<",e:">",k:a,r:10,c:["self"]}]}}}();hljs.LANGUAGES.r={dM:{c:[hljs.HCM,{cN:"number",b:"\\b0[xX][0-9a-fA-F]+[Li]?\\b",e:hljs.IMMEDIATE_RE,r:0},{cN:"number",b:"\\b\\d+(?:[eE][+\\-]?\\d*)?L\\b",e:hljs.IMMEDIATE_RE,r:0},{cN:"number",b:"\\b\\d+\\.(?!\\d)(?:i\\b)?",e:hljs.IMMEDIATE_RE,r:1},{cN:"number",b:"\\b\\d+(?:\\.\\d*)?(?:[eE][+\\-]?\\d*)?i?\\b",e:hljs.IMMEDIATE_RE,r:0},{cN:"number",b:"\\.\\d+(?:[eE][+\\-]?\\d*)?i?\\b",e:hljs.IMMEDIATE_RE,r:1},{cN:"keyword",b:"(?:tryCatch|library|setGeneric|setGroupGeneric)\\b",e:hljs.IMMEDIATE_RE,r:10},{cN:"keyword",b:"\\.\\.\\.",e:hljs.IMMEDIATE_RE,r:10},{cN:"keyword",b:"\\.\\.\\d+(?![\\w.])",e:hljs.IMMEDIATE_RE,r:10},{cN:"keyword",b:"\\b(?:function)",e:hljs.IMMEDIATE_RE,r:2},{cN:"keyword",b:"(?:if|in|break|next|repeat|else|for|return|switch|while|try|stop|warning|require|attach|detach|source|setMethod|setClass)\\b",e:hljs.IMMEDIATE_RE,r:1},{cN:"literal",b:"(?:NA|NA_integer_|NA_real_|NA_character_|NA_complex_)\\b",e:hljs.IMMEDIATE_RE,r:10},{cN:"literal",b:"(?:NULL|TRUE|FALSE|T|F|Inf|NaN)\\b",e:hljs.IMMEDIATE_RE,r:1},{cN:"identifier",b:"[a-zA-Z.][a-zA-Z0-9._]*\\b",e:hljs.IMMEDIATE_RE,r:0},{cN:"operator",b:"<\\-(?!\\s*\\d)",e:hljs.IMMEDIATE_RE,r:2},{cN:"operator",b:"\\->|<\\-",e:hljs.IMMEDIATE_RE,r:1},{cN:"operator",b:"%%|~",e:hljs.IMMEDIATE_RE},{cN:"operator",b:">=|<=|==|!=|\\|\\||&&|=|\\+|\\-|\\*|/|\\^|>|<|!|&|\\||\\$|:",e:hljs.IMMEDIATE_RE,r:0},{cN:"operator",b:"%",e:"%",i:"\\n",r:1},{cN:"identifier",b:"`",e:"`",r:0},{cN:"string",b:'"',e:'"',c:[hljs.BE],r:0},{cN:"string",b:"'",e:"'",c:[hljs.BE],r:0},{cN:"paren",b:"[[({\\])}]",e:hljs.IMMEDIATE_RE,r:0}]}};
hljs.initHighlightingOnLoad();
</script>


<!-- MathJax scripts -->
<script type="text/javascript" src="https://c328740.ssl.cf1.rackcdn.com/mathjax/2.0-latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML">
</script>



</head>

<body>
<p>This exercise examines the first example shown in <br/>
<a href="http://www.jstatsoft.org/v48/i02/paper">http://www.jstatsoft.org/v48/i02/paper</a>.<br/>
It&#39;s a three-factor confirmatory factor analysis example with three items per factor.<br/>
All three latent factors are permitted to correlate.</p>

<ul>
<li><code>x1</code> to <code>x3</code> load on a <code>visual</code> factor</li>
<li><code>x4</code> to <code>x6</code> load on a <code>textual</code> factor</li>
<li><code>x7</code> to <code>x9</code> load on a <code>speed</code> factor</li>
</ul>

<pre><code class="r">library(&#39;lavaan&#39;)
library(&#39;Hmisc&#39;)
cases &lt;- HolzingerSwineford1939
</code></pre>

<h1>Quick examination of data</h1>

<pre><code class="r">str(cases)
</code></pre>

<pre><code>## &#39;data.frame&#39;:    301 obs. of  15 variables:
##  $ id    : int  1 2 3 4 5 6 7 8 9 11 ...
##  $ sex   : int  1 2 2 1 2 2 1 2 2 2 ...
##  $ ageyr : int  13 13 13 13 12 14 12 12 13 12 ...
##  $ agemo : int  1 7 1 2 2 1 1 2 0 5 ...
##  $ school: Factor w/ 2 levels &quot;Grant-White&quot;,..: 2 2 2 2 2 2 2 2 2 2 ...
##  $ grade : int  7 7 7 7 7 7 7 7 7 7 ...
##  $ x1    : num  3.33 5.33 4.5 5.33 4.83 ...
##  $ x2    : num  7.75 5.25 5.25 7.75 4.75 5 6 6.25 5.75 5.25 ...
##  $ x3    : num  0.375 2.125 1.875 3 0.875 ...
##  $ x4    : num  2.33 1.67 1 2.67 2.67 ...
##  $ x5    : num  5.75 3 1.75 4.5 4 3 6 4.25 5.75 5 ...
##  $ x6    : num  1.286 1.286 0.429 2.429 2.571 ...
##  $ x7    : num  3.39 3.78 3.26 3 3.7 ...
##  $ x8    : num  5.75 6.25 3.9 5.3 6.3 6.65 6.2 5.15 4.65 4.55 ...
##  $ x9    : num  6.36 7.92 4.42 4.86 5.92 ...
</code></pre>

<pre><code class="r">Hmisc::describe(cases)
</code></pre>

<pre><code>## cases 
## 
##  15  Variables      301  Observations
## ---------------------------------------------------------------------------
## id 
##       n missing  unique    Mean     .05     .10     .25     .50     .75 
##     301       0     301   176.6      17      33      82     163     272 
##     .90     .95 
##     318     335 
## 
## lowest :   1   2   3   4   5, highest: 346 347 348 349 351 
## ---------------------------------------------------------------------------
## sex 
##       n missing  unique    Mean 
##     301       0       2   1.515 
## 
## 1 (146, 49%), 2 (155, 51%) 
## ---------------------------------------------------------------------------
## ageyr 
##       n missing  unique    Mean 
##     301       0       6      13 
## 
##           11  12  13 14 15 16
## Frequency  8 101 110 55 20  7
## %          3  34  37 18  7  2
## ---------------------------------------------------------------------------
## agemo 
##       n missing  unique    Mean     .05     .10     .25     .50     .75 
##     301       0      12   5.375       0       1       2       5       8 
##     .90     .95 
##      10      11 
## 
##            0  1  2  3  4  5  6  7  8  9 10 11
## Frequency 22 31 26 26 27 27 21 25 26 23 19 28
## %          7 10  9  9  9  9  7  8  9  8  6  9
## ---------------------------------------------------------------------------
## school 
##       n missing  unique 
##     301       0       2 
## 
## Grant-White (145, 48%), Pasteur (156, 52%) 
## ---------------------------------------------------------------------------
## grade 
##       n missing  unique    Mean 
##     300       1       2   7.477 
## 
## 7 (157, 52%), 8 (143, 48%) 
## ---------------------------------------------------------------------------
## x1 
##       n missing  unique    Mean     .05     .10     .25     .50     .75 
##     301       0      35   4.936   3.000   3.333   4.167   5.000   5.667 
##     .90     .95 
##   6.333   6.667 
## 
## lowest : 0.6667 1.6667 1.8333 2.0000 2.6667
## highest: 7.0000 7.1667 7.3333 7.5000 8.5000 
## ---------------------------------------------------------------------------
## x2 
##       n missing  unique    Mean     .05     .10     .25     .50     .75 
##     301       0      25   6.088    4.50    4.75    5.25    6.00    6.75 
##     .90     .95 
##    7.75    8.50 
## 
## lowest : 2.25 3.50 3.75 4.00 4.25, highest: 8.25 8.50 8.75 9.00 9.25 
## ---------------------------------------------------------------------------
## x3 
##       n missing  unique    Mean     .05     .10     .25     .50     .75 
##     301       0      35    2.25   0.625   0.875   1.375   2.125   3.125 
##     .90     .95 
##   4.000   4.250 
## 
## lowest : 0.250 0.375 0.500 0.625 0.750
## highest: 4.000 4.125 4.250 4.375 4.500 
## ---------------------------------------------------------------------------
## x4 
##       n missing  unique    Mean     .05     .10     .25     .50     .75 
##     301       0      20   3.061   1.333   1.667   2.333   3.000   3.667 
##     .90     .95 
##   4.667   5.000 
## 
## lowest : 0.0000 0.3333 0.6667 1.0000 1.3333
## highest: 5.0000 5.3333 5.6667 6.0000 6.3333 
## ---------------------------------------------------------------------------
## x5 
##       n missing  unique    Mean     .05     .10     .25     .50     .75 
##     301       0      25   4.341    2.00    2.50    3.50    4.50    5.25 
##     .90     .95 
##    6.00    6.25 
## 
## lowest : 1.00 1.25 1.50 1.75 2.00, highest: 6.00 6.25 6.50 6.75 7.00 
## ---------------------------------------------------------------------------
## x6 
##       n missing  unique    Mean     .05     .10     .25     .50     .75 
##     301       0      40   2.186  0.7143  1.0000  1.4286  2.0000  2.7143 
##     .90     .95 
##  3.7143  4.2857 
## 
## lowest : 0.1429 0.2857 0.4286 0.5714 0.7143
## highest: 5.1429 5.4286 5.5714 5.8571 6.1429 
## ---------------------------------------------------------------------------
## x7 
##       n missing  unique    Mean     .05     .10     .25     .50     .75 
##     301       0      97   4.186   2.435   2.826   3.478   4.087   4.913 
##     .90     .95 
##   5.696   5.870 
## 
## lowest : 1.304 1.870 2.000 2.043 2.130
## highest: 6.652 6.826 6.957 7.261 7.435 
## ---------------------------------------------------------------------------
## x8 
##       n missing  unique    Mean     .05     .10     .25     .50     .75 
##     301       0      84   5.527    3.90    4.20    4.85    5.50    6.10 
##     .90     .95 
##    6.80    7.20 
## 
## lowest :  3.05  3.50  3.60  3.65  3.70
## highest:  8.00  8.05  8.30  9.10 10.00 
## ---------------------------------------------------------------------------
## x9 
##       n missing  unique    Mean     .05     .10     .25     .50     .75 
##     301       0     129   5.374   3.750   4.111   4.750   5.417   6.083 
##     .90     .95 
##   6.667   7.000 
## 
## lowest : 2.778 3.111 3.222 3.278 3.306
## highest: 7.528 7.611 7.917 8.611 9.250 
## ---------------------------------------------------------------------------
</code></pre>

<p>The data set include <code>301</code> observations. It includes a few demographic variables (e.g., sex, age in years and months, school, and grade). It includes nine variables  that are the observed test scores used in the subsequent CFA.</p>

<h1>Fit CFA</h1>

<pre><code class="r">m1_model &lt;- &#39; visual  =~ x1 + x2 + x3
              textual =~ x4 + x5 + x6
              speed   =~ x7 + x8 + x9
&#39;

m1_fit &lt;- cfa(m1_model, data=cases)
</code></pre>

<ul>
<li>model syntax is specified as a character variable</li>
<li><code>cfa</code> is one model fitting function in <code>lavaan</code>. The command includes many options. Data can be specified as a data frame, as it is here using the <code>data</code> argument. Alternatively covariance matrix, vector of means, and sample size can be specified.</li>
<li>From what I can tell, <code>lavaan</code> is the parent model fitting function that can take a <code>model.type</code> argument of <code>&#39;cfa&#39;</code>, <code>&#39;sem&#39;</code>, or <code>&#39;growth&#39;</code>. Thus, the arguments to <code>model.type</code> are functions themselves which just call <code>lavaan</code> with particular argument values.</li>
</ul>

<h2>Show parameter table</h2>

<pre><code class="r">parTable(m1_fit)
</code></pre>

<pre><code>##    id     lhs op     rhs user group free ustart exo label eq.id unco
## 1   1  visual =~      x1    1     1    0      1   0           0    0
## 2   2  visual =~      x2    1     1    1     NA   0           0    1
## 3   3  visual =~      x3    1     1    2     NA   0           0    2
## 4   4 textual =~      x4    1     1    0      1   0           0    0
## 5   5 textual =~      x5    1     1    3     NA   0           0    3
## 6   6 textual =~      x6    1     1    4     NA   0           0    4
## 7   7   speed =~      x7    1     1    0      1   0           0    0
## 8   8   speed =~      x8    1     1    5     NA   0           0    5
## 9   9   speed =~      x9    1     1    6     NA   0           0    6
## 10 10      x1 ~~      x1    0     1    7     NA   0           0    7
## 11 11      x2 ~~      x2    0     1    8     NA   0           0    8
## 12 12      x3 ~~      x3    0     1    9     NA   0           0    9
## 13 13      x4 ~~      x4    0     1   10     NA   0           0   10
## 14 14      x5 ~~      x5    0     1   11     NA   0           0   11
## 15 15      x6 ~~      x6    0     1   12     NA   0           0   12
## 16 16      x7 ~~      x7    0     1   13     NA   0           0   13
## 17 17      x8 ~~      x8    0     1   14     NA   0           0   14
## 18 18      x9 ~~      x9    0     1   15     NA   0           0   15
## 19 19  visual ~~  visual    0     1   16     NA   0           0   16
## 20 20 textual ~~ textual    0     1   17     NA   0           0   17
## 21 21   speed ~~   speed    0     1   18     NA   0           0   18
## 22 22  visual ~~ textual    0     1   19     NA   0           0   19
## 23 23  visual ~~   speed    0     1   20     NA   0           0   20
## 24 24 textual ~~   speed    0     1   21     NA   0           0   21
</code></pre>

<ul>
<li><p>What do the columns mean?</p>

<ul>
<li><code>id</code>: numeric identifier for the parameter</li>
<li><code>lhs</code>: left hand side variable name</li>
<li><code>op</code>: operator (see page 7 of <a href="http://www.jstatsoft.org/v48/i02/paper">http://www.jstatsoft.org/v48/i02/paper</a>); <code>=~</code> 
is manifested by; <code>~~</code> is correlated with.</li>
<li><code>rhs</code>: right hand side variable name</li>
<li><code>user</code>: 1 if parameter was specified by the user, 0 otherwise</li>
<li><code>group</code>: presumably used in multiple group analysis</li>
<li><code>free</code>: Nonzero elements are free parameters in the model</li>
<li><code>ustart</code>: The value specified for fixed parameters</li>
<li><code>exo</code>: ???</li>
<li><code>label</code>: Probably just an optional label???</li>
<li><code>eq.id</code>: ??? </li>
<li><code>unco</code>: ???</li>
</ul></li>
<li><p>The model syntax used in <code>lavaan</code> incorporates a lot of parameters by default to permit a tidy model syntax. The exact nature of these parameters is also determined by options in the <code>cfa</code>, <code>sem</code> and other model fitting fucntions.</p></li>
<li><p><code>parTable</code> is a method</p></li>
</ul>

<p>It shows that the latent factors are allowed to intercorrelate. The <code>cfa</code> function has an an argument <code>orthogonal</code>. It defaults to FALSE which permits correlated factors.</p>

<pre><code class="r">parTable(cfa(m1_model, data=cases, orthogonal=TRUE))[22:24, ]
</code></pre>

<pre><code>##    id     lhs op     rhs user group free ustart exo label eq.id unco
## 22 22  visual ~~ textual    0     1    0      0   0           0    0
## 23 23  visual ~~   speed    0     1    0      0   0           0    0
## 24 24 textual ~~   speed    0     1    0      0   0           0    0
</code></pre>

<p>When <code>orthogonal=TRUE</code> is specified, the covariance of latent factors is constrained to zero. This is reflected in <code>free=0</code> (i.e., it&#39;s not free to vary) and <code>ustart=0</code> (the constrained value is zero) in the parameter table.</p>

<p>Returning to the original parameter table:</p>

<ul>
<li>Variance parameters (<code>op=~~</code> where <code>lhs</code> is the same as <code>rhs</code>) are included for all observed and latent variables.</li>
</ul>

<h2>Summarise fit</h2>

<pre><code class="r">summary(m1_fit)
</code></pre>

<pre><code>## lavaan (0.4-14) converged normally after 41 iterations
## 
##   Number of observations                           301
## 
##   Estimator                                         ML
##   Minimum Function Chi-square                   85.306
##   Degrees of freedom                                24
##   P-value                                        0.000
## 
## Parameter estimates:
## 
##   Information                                 Expected
##   Standard Errors                             Standard
## 
##                    Estimate  Std.err  Z-value  P(&gt;|z|)
## Latent variables:
##   visual =~
##     x1                1.000
##     x2                0.553    0.100    5.554    0.000
##     x3                0.729    0.109    6.685    0.000
##   textual =~
##     x4                1.000
##     x5                1.113    0.065   17.014    0.000
##     x6                0.926    0.055   16.703    0.000
##   speed =~
##     x7                1.000
##     x8                1.180    0.165    7.152    0.000
##     x9                1.082    0.151    7.155    0.000
## 
## Covariances:
##   visual ~~
##     textual           0.408    0.074    5.552    0.000
##     speed             0.262    0.056    4.660    0.000
##   textual ~~
##     speed             0.173    0.049    3.518    0.000
## 
## Variances:
##     x1                0.549    0.114
##     x2                1.134    0.102
##     x3                0.844    0.091
##     x4                0.371    0.048
##     x5                0.446    0.058
##     x6                0.356    0.043
##     x7                0.799    0.081
##     x8                0.488    0.074
##     x9                0.566    0.071
##     visual            0.809    0.145
##     textual           0.979    0.112
##     speed             0.384    0.086
## 
</code></pre>

<p>The default <code>summary</code> method shows \( \chi^2 \), \( df \), p-value for the overall model, unstandardised parameter estimates, in some cases with significance tests.</p>

<h2>Getting fit statistics</h2>

<p>There are multiple ways of getting fit statistics</p>

<pre><code class="r">fitMeasures(m1_fit)
</code></pre>

<pre><code>##             chisq                df            pvalue    baseline.chisq 
##            85.306            24.000             0.000           918.852 
##       baseline.df   baseline.pvalue               cfi               tli 
##            36.000             0.000             0.931             0.896 
##              logl unrestricted.logl              npar               aic 
##         -3737.745         -3695.092            21.000          7517.490 
##               bic            ntotal              bic2             rmsea 
##          7595.339           301.000          7528.739             0.092 
##    rmsea.ci.lower    rmsea.ci.upper      rmsea.pvalue              srmr 
##             0.071             0.114             0.001             0.065 
</code></pre>

<pre><code class="r"># equivalent to:
# inspect(m1_fit, &#39;fit.measures&#39;)

fitMeasures(m1_fit)[&#39;rmsea&#39;]
</code></pre>

<pre><code>##   rmsea 
## 0.09212 
</code></pre>

<pre><code class="r">fitMeasures(m1_fit, c(&#39;rmsea&#39;, &#39;rmsea.ci.lower&#39;, &#39;rmsea.ci.upper&#39;))
</code></pre>

<pre><code>##          rmsea rmsea.ci.lower rmsea.ci.upper 
##          0.092          0.071          0.114 
</code></pre>

<pre><code class="r">

summary(m1_fit, fit.measures=TRUE)
</code></pre>

<pre><code>## lavaan (0.4-14) converged normally after 41 iterations
## 
##   Number of observations                           301
## 
##   Estimator                                         ML
##   Minimum Function Chi-square                   85.306
##   Degrees of freedom                                24
##   P-value                                        0.000
## 
## Chi-square test baseline model:
## 
##   Minimum Function Chi-square                  918.852
##   Degrees of freedom                                36
##   P-value                                        0.000
## 
## Full model versus baseline model:
## 
##   Comparative Fit Index (CFI)                    0.931
##   Tucker-Lewis Index (TLI)                       0.896
## 
## Loglikelihood and Information Criteria:
## 
##   Loglikelihood user model (H0)              -3737.745
##   Loglikelihood unrestricted model (H1)      -3695.092
## 
##   Number of free parameters                         21
##   Akaike (AIC)                                7517.490
##   Bayesian (BIC)                              7595.339
##   Sample-size adjusted Bayesian (BIC)         7528.739
## 
## Root Mean Square Error of Approximation:
## 
##   RMSEA                                          0.092
##   90 Percent Confidence Interval          0.071  0.114
##   P-value RMSEA &lt;= 0.05                          0.001
## 
## Standardized Root Mean Square Residual:
## 
##   SRMR                                           0.065
## 
## Parameter estimates:
## 
##   Information                                 Expected
##   Standard Errors                             Standard
## 
##                    Estimate  Std.err  Z-value  P(&gt;|z|)
## Latent variables:
##   visual =~
##     x1                1.000
##     x2                0.553    0.100    5.554    0.000
##     x3                0.729    0.109    6.685    0.000
##   textual =~
##     x4                1.000
##     x5                1.113    0.065   17.014    0.000
##     x6                0.926    0.055   16.703    0.000
##   speed =~
##     x7                1.000
##     x8                1.180    0.165    7.152    0.000
##     x9                1.082    0.151    7.155    0.000
## 
## Covariances:
##   visual ~~
##     textual           0.408    0.074    5.552    0.000
##     speed             0.262    0.056    4.660    0.000
##   textual ~~
##     speed             0.173    0.049    3.518    0.000
## 
## Variances:
##     x1                0.549    0.114
##     x2                1.134    0.102
##     x3                0.844    0.091
##     x4                0.371    0.048
##     x5                0.446    0.058
##     x6                0.356    0.043
##     x7                0.799    0.081
##     x8                0.488    0.074
##     x9                0.566    0.071
##     visual            0.809    0.145
##     textual           0.979    0.112
##     speed             0.384    0.086
## 
</code></pre>

<ul>
<li>I assume that lavaan uses S4 classes which makes extracting elements a little different to S3 classes.</li>
<li>The above code shows how to extract fit measures.</li>
<li>While it is not clear hear, it appears that <code>rmsea.ci.lower</code> and <code>rmsea.ci.upper</code> refer to 90% lower and upper confidence intervals.</li>
<li>Adding <code>fit.measures=TRUE</code> provides a way of displaying </li>
</ul>

<h2>Modification indices</h2>

<pre><code class="r">m1_mod &lt;- modificationIndices(m1_fit)
head(m1_mod[order(m1_mod$mi, decreasing=TRUE), ], 10)
</code></pre>

<pre><code>##        lhs op rhs     mi    epc sepc.lv sepc.all sepc.nox
## 1   visual =~  x9 36.411  0.577   0.519    0.515    0.515
## 2       x7 ~~  x8 34.145  0.536   0.536    0.488    0.488
## 3   visual =~  x7 18.631 -0.422  -0.380   -0.349   -0.349
## 4       x8 ~~  x9 14.946 -0.423  -0.423   -0.415   -0.415
## 5  textual =~  x3  9.151 -0.272  -0.269   -0.238   -0.238
## 6       x2 ~~  x7  8.918 -0.183  -0.183   -0.143   -0.143
## 7  textual =~  x1  8.903  0.350   0.347    0.297    0.297
## 8       x2 ~~  x3  8.532  0.218   0.218    0.164    0.164
## 9       x3 ~~  x5  7.858 -0.130  -0.130   -0.089   -0.089
## 10  visual =~  x5  7.441 -0.210  -0.189   -0.147   -0.147
</code></pre>

<ul>
<li>The <code>modificationIndices</code> function returns modification indices and expected parameter changes (EPCs). </li>
<li>The second line above sorts the rows of the modification indices table in decreasing order and shows those parameters with the 10 largest values.</li>
</ul>

<pre><code class="r">m2_model &lt;- &#39; visual  =~ x1 + x2 + x3 + x9
              textual =~ x4 + x5 + x6
              speed   =~ x7 + x8 + x9
&#39;

m2_fit &lt;- cfa(m2_model, data=cases)
anova(m1_fit, m2_fit)
</code></pre>

<pre><code>## Chi Square Difference Test
## 
##        Df  AIC  BIC Chisq Chisq diff Df diff Pr(&gt;Chisq)    
## m2_fit 23 7487 7568  52.4                                  
## m1_fit 24 7517 7595  85.3       32.9       1    9.6e-09 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1 
</code></pre>

<ul>
<li>Note that more than one empty line at the end of the model definition seems to cause an error.</li>
<li>TODO: Work out why the change in \( \chi^2 \) 
<code>32.9234</code>
is different to the value of the modification index
<code>36.411</code>.</li>
</ul>

<h2>Standardised parameters</h2>

<pre><code class="r">summary(m1_fit)
</code></pre>

<pre><code>## lavaan (0.4-14) converged normally after 41 iterations
## 
##   Number of observations                           301
## 
##   Estimator                                         ML
##   Minimum Function Chi-square                   85.306
##   Degrees of freedom                                24
##   P-value                                        0.000
## 
## Parameter estimates:
## 
##   Information                                 Expected
##   Standard Errors                             Standard
## 
##                    Estimate  Std.err  Z-value  P(&gt;|z|)
## Latent variables:
##   visual =~
##     x1                1.000
##     x2                0.553    0.100    5.554    0.000
##     x3                0.729    0.109    6.685    0.000
##   textual =~
##     x4                1.000
##     x5                1.113    0.065   17.014    0.000
##     x6                0.926    0.055   16.703    0.000
##   speed =~
##     x7                1.000
##     x8                1.180    0.165    7.152    0.000
##     x9                1.082    0.151    7.155    0.000
## 
## Covariances:
##   visual ~~
##     textual           0.408    0.074    5.552    0.000
##     speed             0.262    0.056    4.660    0.000
##   textual ~~
##     speed             0.173    0.049    3.518    0.000
## 
## Variances:
##     x1                0.549    0.114
##     x2                1.134    0.102
##     x3                0.844    0.091
##     x4                0.371    0.048
##     x5                0.446    0.058
##     x6                0.356    0.043
##     x7                0.799    0.081
##     x8                0.488    0.074
##     x9                0.566    0.071
##     visual            0.809    0.145
##     textual           0.979    0.112
##     speed             0.384    0.086
## 
</code></pre>

<pre><code class="r">standardizedSolution(m1_fit)
</code></pre>

<pre><code>##        lhs op     rhs est.std se  z pvalue
## 1   visual =~      x1   0.772 NA NA     NA
## 2   visual =~      x2   0.424 NA NA     NA
## 3   visual =~      x3   0.581 NA NA     NA
## 4  textual =~      x4   0.852 NA NA     NA
## 5  textual =~      x5   0.855 NA NA     NA
## 6  textual =~      x6   0.838 NA NA     NA
## 7    speed =~      x7   0.570 NA NA     NA
## 8    speed =~      x8   0.723 NA NA     NA
## 9    speed =~      x9   0.665 NA NA     NA
## 10      x1 ~~      x1   0.404 NA NA     NA
## 11      x2 ~~      x2   0.821 NA NA     NA
## 12      x3 ~~      x3   0.662 NA NA     NA
## 13      x4 ~~      x4   0.275 NA NA     NA
## 14      x5 ~~      x5   0.269 NA NA     NA
## 15      x6 ~~      x6   0.298 NA NA     NA
## 16      x7 ~~      x7   0.676 NA NA     NA
## 17      x8 ~~      x8   0.477 NA NA     NA
## 18      x9 ~~      x9   0.558 NA NA     NA
## 19  visual ~~  visual   1.000 NA NA     NA
## 20 textual ~~ textual   1.000 NA NA     NA
## 21   speed ~~   speed   1.000 NA NA     NA
## 22  visual ~~ textual   0.459 NA NA     NA
## 23  visual ~~   speed   0.471 NA NA     NA
## 24 textual ~~   speed   0.283 NA NA     NA
</code></pre>

</body>

</html>

