# Lavaan Cheat Sheet
## Assumptions
* `Data` is data frame
* `model` is the lavaan model syntax character variable
* `fit` is an object of class `lavaan` typically returned from functions `cfa`, `sem`, `growth`, and `lavaan`
* `m1_fit` and `m2_fit` are used for showing model comparison of `lavaan` objects.


## Documentation tips
* Introduction: http://users.ugent.be/~yrosseel/lavaan/lavaanIntroduction.pdf
* Basic model commmands: `?cfa ?sem ?lavaan`: 
* Extracting elements: `?inspect`

## Model fitting
| Name | Command |
-------| -------------
fit CFA to data | `cfa(model, data=Data)`
fit SEM to data | `sem(model, data=Data)`
standardised solution | `sem(model, data=Data, std.ov=TRUE)`
orthogonal factors | `cfa(model, data=Data, orthogonal=TRUE)`


## Matrices
| Name | Command |
-------| -------------
Factor covariance matrix | `inspect(fit, "coefficients")$psi`
Fitted covariance matrix | `fitted(fit)$cov`
Observed covariance matrix | `inspect(fit, 'sampstat')$cov`
Residual covariance matrix | `resid(fit)$cov`
Factor correlation matrix | `cov2cor(inspect(fit, "coefficients")$psi)` or use covariance command with standardised solution e.g.,  `cfa(..., std.ov=TRUE)` 
Residual correlation matrix

## Fit Measures
| Name | Command |
-------| -------------
Fit measures: | `fitMeasures(fit)` 
Specific fit measures e.g.: | `fitMeasures(fit)[c('chisq', 'df', 'pvalue', 'cfi', 'rmsea', 'srmr')]`


## Parameters
| Name | Command |
-------| -------------
Parameter information | `parTable(fit)`
Standardised estimates | `parameterestimates(m1_fit, standardized=TRUE)` or `standardizedSolution(fit)` or `summary(fit, standardized=TRUE)` or `inspect(fit, 'std.coef')`
Unstandardised estimates | `parameterestimates(fit)` or `coef(fit)`
R-squared | `inspect(fit, 'r2')`



## Compare models

| Name | Command |
-------| -------------
Compare fit measures | `cbind(m1=inspect(m1_fit, 'fit.measures'), m2=inspect(m2_fit, 'fit.measures'))`
Chi-square difference test | `anova(m1_fit, m2_fit)`

## Model improvement
| Name | Command |
-------| -------------
Modification indices | `mod_ind <- modificationindices(fit)`
10 greatest | `head(mod_ind[order(mod_ind$mi, decreasing=TRUE), ], 10)`
mi > 5 | `subset(mod_ind[order(mod_ind$mi, decreasing=TRUE), ], mi > 5)`

